#!/bin/bash
set -e

# Wait for Docker daemon to be ready
while ! docker info >/dev/null 2>&1; do
    echo "Waiting for Docker daemon to be ready..."
    sleep 2
done

SRC=/usr/local/bin/middle_earth
DATA=$SRC/data

###########################
## Nazgûl containers
###########################

nazguls_array=('The Witch-king'  'Khamûl' 'Dark Marshal' 'Betrayer' 'Undying' 'Dwimmerleik' 'Knight of Umbar' 'Tainted' 'Shadow Lord')



for i in "${!nazguls_array[@]}"; do
    if ! docker start nazgul$i >> /dev/null; then
        docker run --name nazgul$i -d --restart always -p 600$i:5678 nazgul -text="${nazguls_array[i]}" || { echo "Failed to start or create nazgul$i"; exit 1; }
    fi
done

###########################
## Prancing pony container
###########################

cd /pony
docker build . -t prancing_pony || { echo "Failed to build prancing_pony"; exit 1; }
docker run -d -v /home:/home -v /etc/shadow:/etc/shadow -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -v /var/lib/middle_earth:/var/lib/middle_earth -h the-prancing-pony --name prancing_pony prancing_pony || { echo "Failed to run prancing_pony"; exit 1; }
