#!/bin/bash

function update_stage () {
  DBID=$(( `id -u` + 1000))
  DBIP=`ip route|grep default|awk '{print $3}'`
  mariadb --ssl=OFF -uroot -proot -h $DBIP middle_earth -e "UPDATE stages SET stage_completed = 2 WHERE user_id = $DBID"
}
function keypause () {

	read -n 1 -r -s -p "Press any key to continue..." key
}

DIR=/usr/local/bin/middle_earth
DATA=$DIR/data
update_stage
clear
$DIR/showlines $DATA/ppony.ansi
keypause
clear
$DIR/showlines $DATA/story_pony.txt
keypause
clear
helpme

